/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BacktestResult: typeof import('./src/components/BacktestResult/index.vue')['default']
    HeatMap: typeof import('./src/components/Charts/HeatMap.vue')['default']
    KLineChart: typeof import('./src/components/KLineChart/index.vue')['default']
    LineChart: typeof import('./src/components/Charts/LineChart.vue')['default']
    RealTimeQuote: typeof import('./src/components/RealTimeQuote/index.vue')['default']
    StrategyAnalysis: typeof import('./src/components/StrategyAnalysis/index.vue')['default']
    StrategyConfig: typeof import('./src/components/StrategyConfig/index.vue')['default']
    TestComponent: typeof import('./src/components/TestComponent.vue')['default']
    TimeAndCostConfig: typeof import('./src/components/TimeAndCostConfig/index.vue')['default']
    TimingConfig: typeof import('./src/components/TimingConfig/index.vue')['default']
    TradeAnalysis: typeof import('./src/components/TradeAnalysis/index.vue')['default']
    TradeRecords: typeof import('./src/components/TradeRecords/index.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCalendar: typeof import('vant/es')['Calendar']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanSearch: typeof import('vant/es')['Search']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
  }
}
